<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns="http://www.netex.org.uk/netex" xmlns:netex="http://www.netex.org.uk/netex" xmlns:siri="http://www.siri.org.uk/siri" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://www.netex.org.uk/netex" elementFormDefault="qualified" attributeFormDefault="unqualified" version="2.0" id="netex_customerAccountLogEntries_support">
	<xsd:include schemaLocation="../part3_salesTransactions/netex_salesContract_support.xsd"/>
	<!-- =============================================================== -->
	<xsd:annotation>
		<xsd:appinfo>
			<Metadata xmlns="http://www.govtalk.gov.uk/CM/gms-xs">
				<Aggregation>main schema</Aggregation>
				<Audience>e-service developers</Audience>
				<Coverage>Europe</Coverage>
				<Creator>Arne Seime</Creator>
				<Date>
					<Created>2020-11-20</Created>
					Align with TM
					Add CustomerAccountEntry as a base type for Customer Account log entries
					Add CustomerRegistrationEntry and CustomerDeregistrationEntry as concrete CustomerAccountEntries
				</Date>
				<Description>
					<p>NeTEx is a European CEN standard for the exchange of Public Transport data including timetables.</p>
					<p>This sub-schema describes the CUSTOMER ACCOUNT LOG ENTRY types.</p>
				</Description>
				<Format>
					<MediaType>text/xml</MediaType>
					<Syntax>http://www.w3.org/2001/XMLSchema</Syntax>
					<Description>XML schema, W3C Recommendation 2001</Description>
				</Format>
				<Language>[ISO 639-2/B] ENG</Language>
				<Rights>Unclassified
					 <Copyright>CEN, Crown Copyright 2009-2023</Copyright>
				</Rights>
				<Source>
					<ul>
						<li>Derived from the Transmodel, VDV, TransXChange, NEPTUNE, BISON and Trident standards.</li>
					</ul>
				</Source>
				<Status>Version 1.0 Draft for approval</Status>
				<Subject>
					<Category>Arts, recreation and travel, Tourism, Travel (tourism), Transport,
Air transport, Airports,
Ports and maritime transport, Ferries (marine),
Public transport, Bus services, Coach services, Bus stops and stations,
Rail transport, Railway stations and track, Train services, Underground trains,
Business and industry, Transport, Air transport , Ports and maritime transport, Public transport,
Rail transport, Roads and Road transport
</Category>
					<Project>CEN TC278 WG3 SG9.</Project>
				</Subject>
				<Title>NeTEx CUSTOMER ACCOUNT ENTRies identifier types.</Title>
				<Type>Standard</Type>
			</Metadata>
		</xsd:appinfo>
		<xsd:documentation>NeTEx: CUSTOMER ACCOUNT ENTRies identifier types.</xsd:documentation>
	</xsd:annotation>
	<!-- ====TYPE OF CUSTOMER ACCOUNT ENTRY================================================== -->
	<xsd:complexType name="typeOfCustomerAccountEntryRefs_RelStructure">
		<xsd:annotation>
			<xsd:documentation>Type for a list of TYPEs OF CUSTOMER ACCOUNT ENTRY.</xsd:documentation>
		</xsd:annotation>
		<xsd:complexContent>
			<xsd:extension base="oneToManyRelationshipStructure">
				<xsd:sequence>
					<xsd:element ref="TypeOfCustomerAccountEntryRef" maxOccurs="unbounded"/>
				</xsd:sequence>
			</xsd:extension>
		</xsd:complexContent>
	</xsd:complexType>
	<xsd:simpleType name="TypeOfCustomerAccountEntryIdType">
		<xsd:annotation>
			<xsd:documentation>Type for identifier of a TYPE OF CUSTOMER ACCOUNT ENTRY.</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="TypeOfValueIdType"/>
	</xsd:simpleType>
	<xsd:element name="TypeOfCustomerAccountEntryRef" type="TypeOfCustomerAccountEntryRefStructure" substitutionGroup="TypeOfEntityRef">
		<xsd:annotation>
			<xsd:documentation>Reference to a TYPE OF CUSTOMER ACCOUNT ENTRY. +v2.0</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:complexType name="TypeOfCustomerAccountEntryRefStructure">
		<xsd:annotation>
			<xsd:documentation>Type for Reference to a TYPE OF CUSTOMER ACCOUNT ENTRY.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleContent>
			<xsd:restriction base="TypeOfValueRefStructure">
				<xsd:attribute name="ref" type="TypeOfCustomerAccountEntryIdType" use="required">
					<xsd:annotation>
						<xsd:documentation>Identifier of a TYPE OF CUSTOMER ACCOUNT ENTRY.</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
			</xsd:restriction>
		</xsd:simpleContent>
	</xsd:complexType>
	<!-- ====CUSTOMER ACCOUNT ENTRY ======================================= -->
	<xsd:simpleType name="CustomerAccountEntryIdType">
		<xsd:annotation>
			<xsd:documentation>Type for identifier of a CUSTOMER ACCOUNT ENTRY.</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="FareContractEntryIdType"/>
	</xsd:simpleType>
	<xsd:element name="CustomerAccountEntryRef" type="CustomerAccountEntryRefStructure" substitutionGroup="FareContractEntryRef">
		<xsd:annotation>
			<xsd:documentation>Reference to a CUSTOMER ACCOUNT ENTRY.  +v2.0</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:complexType name="CustomerAccountEntryRefStructure">
		<xsd:annotation>
			<xsd:documentation>Type for Reference to a CUSTOMER ACCOUNT ENTRY.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleContent>
			<xsd:restriction base="FareContractEntryRefStructure">
				<xsd:attribute name="ref" type="CustomerAccountEntryIdType" use="required">
					<xsd:annotation>
						<xsd:documentation>Identifier of a CUSTOMER ACCOUNT ENTRY.</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
			</xsd:restriction>
		</xsd:simpleContent>
	</xsd:complexType>
	<!-- ====CUSTOMER PROFILE MODIFICATION  ENTRY ================================== -->
	<xsd:simpleType name="CustomerProfileModificationEntryIdType">
		<xsd:annotation>
			<xsd:documentation>Type for identifier of a CUSTOMER PROFILE MODIFICATION ENTRY.</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="LogEntryIdType"/>
	</xsd:simpleType>
	<xsd:element name="CustomerProfileModificationEntryRef" type="CustomerProfileModificationEntryRefStructure" substitutionGroup="LogEntryRef">
		<xsd:annotation>
			<xsd:documentation>Reference to a CUSTOMER PROFILE MODIFICATION ENTRY. +v2.0</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:complexType name="CustomerProfileModificationEntryRefStructure">
		<xsd:annotation>
			<xsd:documentation>Type for Reference to a CUSTOMER PROFILE MODIFICATION ENTRY.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleContent>
			<xsd:restriction base="LogEntryRefStructure">
				<xsd:attribute name="ref" type="CustomerProfileModificationEntryIdType" use="required">
					<xsd:annotation>
						<xsd:documentation>Identifier of a CUSTOMER PROFILE MODIFICATION ENTRY.</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
			</xsd:restriction>
		</xsd:simpleContent>
	</xsd:complexType>
	<!-- ==== CUSTOMER MEDIA REGISTRATION ENTRY ================================== -->
	<xsd:simpleType name="CustomerMediaRegistrationEntryIdType">
		<xsd:annotation>
			<xsd:documentation>Type for identifier of a CUSTOMER MEDIA REGISTRATION ENTRY.</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="LogEntryIdType"/>
	</xsd:simpleType>
	<xsd:element name="CustomerMediaRegistrationEntryRef" type="CustomerMediaRegistrationEntryRefStructure" substitutionGroup="LogEntryRef">
		<xsd:annotation>
			<xsd:documentation>Reference to a CUSTOMER MEDIA REGISTRATION ENTRY. +v2.0</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:complexType name="CustomerMediaRegistrationEntryRefStructure">
		<xsd:annotation>
			<xsd:documentation>Type for Reference to a CUSTOMER MEDIA REGISTRATION ENTRY.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleContent>
			<xsd:restriction base="LogEntryRefStructure">
				<xsd:attribute name="ref" type="CustomerMediaRegistrationEntryIdType" use="required">
					<xsd:annotation>
						<xsd:documentation>Identifier of a CUSTOMER MEDIA REGISTRATION ENTRY.</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
			</xsd:restriction>
		</xsd:simpleContent>
	</xsd:complexType>
	<!-- ====CUSTOMER REGISTRATION ENTRY ========================================= -->
	<xsd:simpleType name="CustomerRegistrationEntryIdType">
		<xsd:annotation>
			<xsd:documentation>Type for identifier of a CUSTOMER REGISTRATION ENTRY.</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="CustomerAccountEntryIdType"/>
	</xsd:simpleType>
	<xsd:element name="CustomerRegistrationEntryRef" type="CustomerRegistrationEntryRefStructure" abstract="false" substitutionGroup="CustomerAccountEntryRef">
		<xsd:annotation>
			<xsd:documentation>Reference to a CUSTOMER REGISTRATION ENTRY. +v2.0</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:complexType name="CustomerRegistrationEntryRefStructure">
		<xsd:annotation>
			<xsd:documentation>Type for Reference to a CUSTOMER REGISTRATION ENTRY.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleContent>
			<xsd:restriction base="CustomerAccountEntryRefStructure">
				<xsd:attribute name="ref" type="CustomerRegistrationEntryIdType" use="required">
					<xsd:annotation>
						<xsd:documentation>Identifier of a CUSTOMER REGISTRATION ENTRY.</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
			</xsd:restriction>
		</xsd:simpleContent>
	</xsd:complexType>
	<!-- ====CUSTOMER DEREGISTRATION ENTRY =============================================== -->
	<xsd:simpleType name="CustomerDeregistrationEntryIdType">
		<xsd:annotation>
			<xsd:documentation>Type for identifier of a CUSTOMER DEREGISTRATION ENTRY.</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="CustomerAccountEntryIdType"/>
	</xsd:simpleType>
	<xsd:element name="CustomerDeregistrationEntryRef" type="CustomerDeregistrationEntryRefStructure" abstract="false" substitutionGroup="CustomerAccountEntryRef">
		<xsd:annotation>
			<xsd:documentation>Reference to a CUSTOMER DEREGISTRATION ENTRY. +v2.0</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:complexType name="CustomerDeregistrationEntryRefStructure">
		<xsd:annotation>
			<xsd:documentation>Type for Reference to a CUSTOMER DEREGISTRATION ENTRY.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleContent>
			<xsd:restriction base="CustomerAccountEntryRefStructure">
				<xsd:attribute name="ref" type="CustomerDeregistrationEntryIdType" use="required">
					<xsd:annotation>
						<xsd:documentation>Identifier of a CUSTOMER DEREGISTRATION ENTRY.</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
			</xsd:restriction>
		</xsd:simpleContent>
	</xsd:complexType>
	<!-- ====RESTORE CUSTOMER ACCOUNT ENTRY =============================================== -->
	<xsd:simpleType name="RestoreCustomerAccountEntryIdType">
		<xsd:annotation>
			<xsd:documentation>Type for identifier of a RESTORE CUSTOMER ACCOUNT ENTRY.</xsd:documentation>
		</xsd:annotation>
		<xsd:restriction base="CustomerAccountEntryIdType"/>
	</xsd:simpleType>
	<xsd:element name="RestoreCustomerAccountEntryRef" type="RestoreCustomerAccountEntryRefStructure" abstract="false" substitutionGroup="CustomerAccountEntryRef">
		<xsd:annotation>
			<xsd:documentation>Reference to a RESTORE CUSTOMER ACCOUNT ENTRY. +v2.0</xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	<xsd:complexType name="RestoreCustomerAccountEntryRefStructure">
		<xsd:annotation>
			<xsd:documentation>Type for Reference to a RESTORE CUSTOMER ACCOUNT ENTRY.</xsd:documentation>
		</xsd:annotation>
		<xsd:simpleContent>
			<xsd:restriction base="CustomerAccountEntryRefStructure">
				<xsd:attribute name="ref" type="RestoreCustomerAccountEntryIdType" use="required">
					<xsd:annotation>
						<xsd:documentation>Identifier of a RESTORE CUSTOMER ACCOUNT ENTRY.</xsd:documentation>
					</xsd:annotation>
				</xsd:attribute>
			</xsd:restriction>
		</xsd:simpleContent>
	</xsd:complexType>
</xsd:schema>
